[package]
name = "pallet-democracy-precompiles"
version = "0.1.0"
authors = ["PureStake"]
edition = "2018"
description = "A Precompile to make Substrate's pallet-democracy accessible to pallet-evm"

[dependencies]
log = "0.4"
num_enum = { version = "0.5.3", default-features = false }

codec = { package="parity-scale-codec", version="2.0.0", default-features=false }
frame-support = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8", default-features=false }
evm = { version="0.27.0", default-features=false, features=["with-codec"] }
sp-std = { git="https://github.com/paritytech/substrate", default-features=false, branch="polkadot-v0.9.8" }
sp-core = { git="https://github.com/paritytech/substrate", default-features=false, branch="polkadot-v0.9.8" }
sp-io = { git="https://github.com/paritytech/substrate", default-features=false, branch="polkadot-v0.9.8" }
pallet-evm = { git="https://github.com/purestake/frontier", default-features=false, branch="moonbeam-polkadot-pre" }
pallet-democracy = { git="https://github.com/paritytech/substrate", default-features=false, branch="polkadot-v0.9.8" }
frame-system = { git="https://github.com/paritytech/substrate", default-features=false, branch="polkadot-v0.9.8" }
precompile-utils = { path = "../utils", default-features = false }

[dev-dependencies]
sha3 = "0.9"
hex = "0.4"
hex-literal = "0.3.1"
sp-runtime = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8" }
pallet-balances = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8" }
pallet-timestamp = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8" }
pallet-scheduler = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8" }
max-encoded-len = { git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.8", features=["derive"] }
serde = "1.0.100"
derive_more = "0.99"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "evm/std",
    "sp-std/std",
    "sp-core/std",
    "pallet-democracy/std",
    "frame-system/std",
    "pallet-evm/std",
    "precompile-utils/std",
]
